// client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
<script lang="ts" context="module">
    import type { BlobFileFields } from '$lib/repo/api/blob'

    export interface BlobInfo extends BlobFileFields {
        commitID: string
        filePath: string
        repoName: string
        revision: string
    }

    const shCompartment = new Compartment()
    const miscSettingsCompartment = new Compartment()

    const defaultTheme = EditorView.theme({
        '&': {
            width: '100%',
            'min-height': 0,
            color: 'var(--color-code)',
            flex: 1,
        },
        '.cm-scroller': {
            lineHeight: '1rem',
            fontFamily: 'var(--code-font-family)',
            fontSize: 'var(--code-font-size)',
        },
        '.cm-content:focus-visible': {
            outline: 'none',
            boxShadow: 'none',
        },
        '.cm-gutters': {
            'background-color': 'var(--code-bg)',
            border: 'none',
            color: 'var(--line-number-color)',
        },
        '.cm-line': {
            paddingLeft: '0',
        },
        '.selected-line': {
            backgroundColor: 'var(--code-selection-bg)',

            '&:focus': {
                boxShadow: 'none',
            },
        },
        '.highlighted-line': {
            backgroundColor: 'var(--code-selection-bg)',
        },
    })

    const staticExtensions: Extension = [
        // Log uncaught errors that happen in callbacks that we pass to
        // CodeMirror. Without this exception sink, exceptions get silently
        // ignored making it difficult to debug issues caused by uncaught
        // exceptions.
        // eslint-disable-next-line no-console
        EditorView.exceptionSink.of(exception => console.log(exception)),
        EditorView.editable.of(false),
        EditorView.contentAttributes.of({
            // This is required to make the blob view focusable and to make
            // triggering the in-document search (see below) work when Mod-f is
            // pressed
            tabindex: '0',
            // CodeMirror defaults to role="textbox" which does not produce the
            // desired screenreader behavior we want for this component.
            // See https://github.com/sourcegraph/sourcegraph/issues/43375
            role: 'generic',
        }),
        defaultTheme,
        buildLinks.of(true),
    ]

    function configureSyntaxHighlighting(content: string, lsif: string): Extension {
        return lsif ? syntaxHighlight.of({ content, lsif }) : []
    }

    function configureMiscSettings({ wrapLines }: { wrapLines: boolean }): Extension {
        return [wrapLines ? EditorView.lineWrapping : []]
    }
</script>

<script lang="ts">
    import '$lib/highlight.scss'

    import { Compartment, EditorState, StateEffect, type Extension } from '@codemirror/state'
    import { EditorView } from '@codemirror/view'
    import { createEventDispatcher, onMount } from 'svelte'

    import { browser } from '$app/environment'
    import {
        blobPropsFacet,
        selectableLineNumbers,
        syntaxHighlight,
        type SelectedLineRange,
        setSelectedLines,
        isValidLineRange,
        codeIntelAPI as codeIntelAPIFacet,
        buildLinks,
    } from '$lib/web'
    import type { CodeIntelAPI } from '@sourcegraph/shared/src/codeintel/api'

    export let blobInfo: BlobInfo
    export let highlights: string
    export let wrapLines: boolean = false
    export let selectedLines: SelectedLineRange | null = null
    export let codeIntelAPI: CodeIntelAPI

    const dispatch = createEventDispatcher<{ selectline: SelectedLineRange }>()

    let editor: EditorView
    let container: HTMLDivElement | null = null

    function createEditor(container: HTMLDivElement): EditorView {
        const extensions = [
            // @ts-ignore - ugly (temporary?) hack to avoid issues with existing extension (selectableLineNumbers)
            blobPropsFacet.of({
                blobInfo,
            }),
            codeIntelAPIFacet.of(codeIntelAPI),
            staticExtensions,
            selectableLineNumbers({
                onSelection(range) {
                    dispatch('selectline', range)
                },
                initialSelection: selectedLines,
                navigateToLineOnAnyClick: false,
            }),
            miscSettingsCompartment.of(configureMiscSettings({ wrapLines })),
            shCompartment.of(configureSyntaxHighlighting(blobInfo.content, highlights)),
        ]

        const view = new EditorView({
            state: EditorState.create({ doc: blobInfo.content, extensions }),
            parent: container,
        })
        return view
    }

    function updateExtensions(effects: StateEffect<unknown> | readonly StateEffect<unknown>[]) {
        if (editor) {
            editor.dispatch({ effects })
        }
    }

    function updateSelectedLines(range: SelectedLineRange) {
        if (editor) {
            updateExtensions(setSelectedLines.of(range && isValidLineRange(range, editor.state.doc) ? range : null))
        }
    }

    // Update blob content and highlights
    $: updateExtensions(shCompartment.reconfigure(configureSyntaxHighlighting(blobInfo.content, highlights)))
    // Update line wrapping
    $: updateExtensions(miscSettingsCompartment.reconfigure(configureMiscSettings({ wrapLines })))
    // Update selected line
    $: updateSelectedLines(selectedLines)

    $: if (editor && editor?.state.sliceDoc() !== blobInfo.content) {
        editor.dispatch({
            changes: { from: 0, to: editor.state.doc.length, insert: blobInfo.content },
        })
    }

    onMount(() => {
        if (container) {
            editor = createEditor(container)
        }
    })
</script>

{#if browser}
    <div bind:this={container} class="root test-editor" data-editor="codemirror6" />
{:else}
    <div class="root">
        <pre>{blobInfo.content}</pre>
    </div>
{/if}

<style lang="scss">
    .root {
        display: contents;
        overflow: hidden;
    }
    pre {
        margin: 0;
    }
</style>

// client/web/src/repo/blob/CodeMirrorBlob.tsx
/**
 * An experimental implementation of the Blob view using CodeMirror
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import { openSearchPanel } from '@codemirror/search'
import { Compartment, EditorState, Extension } from '@codemirror/state'
import { EditorView } from '@codemirror/view'
import { isEqual } from 'lodash'

import {
    addLineRangeQueryParameter,
    formatSearchParameters,
    toPositionOrRangeQueryParameter,
} from '@sourcegraph/common'
import { editorHeight, useCodeMirror } from '@sourcegraph/shared/src/components/CodeMirrorEditor'
import { Shortcut } from '@sourcegraph/shared/src/react-shortcuts'
import { parseQueryAndHash } from '@sourcegraph/shared/src/util/url'
import { useLocalStorage } from '@sourcegraph/wildcard'

import { useExperimentalFeatures } from '../../stores'

import { BlobInfo, BlobProps, updateBrowserHistoryIfChanged } from './Blob'
import { blobPropsFacet } from './codemirror'
import { showGitBlameDecorations } from './codemirror/blame-decorations'
import { syntaxHighlight } from './codemirror/highlight'
import { pin, updatePin } from './codemirror/hovercard'
import { selectableLineNumbers, SelectedLineRange, selectLines } from './codemirror/linenumbers'
import { search } from './codemirror/search'
import { sourcegraphExtensions } from './codemirror/sourcegraph-extensions'
import { tokensAsLinks } from './codemirror/tokens-as-links'
import { isValidLineRange } from './codemirror/utils'

const staticExtensions: Extension = [
    EditorState.readOnly.of(true),
    EditorView.editable.of(false),
    EditorView.contentAttributes.of({
        // This is required to make the blob view focusable and to make
        // triggering the in-document search (see below) work when Mod-f is
        // pressed
        tabindex: '0',
        // CodeMirror defaults to role="textbox" which does not produce the
        // desired screenreader behavior we want for this component.
        // See https://github.com/sourcegraph/sourcegraph/issues/43375
        role: 'generic',
    }),
    editorHeight({ height: '100%' }),
    EditorView.theme({
        '&': {
            backgroundColor: 'var(--code-bg)',
        },
        '.cm-scroller': {
            fontFamily: 'var(--code-font-family)',
            fontSize: 'var(--code-font-size)',
            lineHeight: '1rem',
        },
        '.cm-gutters': {
            backgroundColor: 'var(--code-bg)',
            borderRight: 'initial',
        },
        '.cm-line': {
            paddingLeft: '1rem',
        },
        '.selected-line': {
            backgroundColor: 'var(--code-selection-bg)',
        },
        '.selected-line:focus': {
            boxShadow: 'none',
        },
        '.highlighted-line': {
            backgroundColor: 'var(--code-selection-bg)',
        },
    }),
]

// Compartments are used to reconfigure some parts of the editor without
// affecting others.

// Compartment to update various smaller settings
const settingsCompartment = new Compartment()
// Compartment to update blame information
const blameDecorationsCompartment = new Compartment()
// Compartment for propagating component props
const blobPropsCompartment = new Compartment()

export const Blob: React.FunctionComponent<BlobProps> = props => {
    const {
        className,
        wrapCode,
        isLightTheme,
        ariaLabel,
        role,
        extensionsController,
        location,
        history,
        blameHunks,
        tokenKeyboardNavigation,

        // Reference panel specific props
        disableStatusBar,
        disableDecorations,
        navigateToLineOnAnyClick,

        overrideBrowserSearchKeybinding,
        'data-testid': dataTestId,
    } = props

    const [useFileSearch, setUseFileSearch] = useLocalStorage('blob.overrideBrowserFindOnPage', true)

    const [container, setContainer] = useState<HTMLDivElement | null>(null)
    // This is used to avoid reinitializing the editor when new locations in the
    // same file are opened inside the reference panel.
    const blobInfo = useDistinctBlob(props.blobInfo)
    const position = useMemo(() => parseQueryAndHash(location.search, location.hash), [location.search, location.hash])
    const hasPin = useMemo(() => urlIsPinned(location.search), [location.search])

    const blobProps = useMemo(() => blobPropsFacet.of(props), [props])

    const settings = useMemo(
        () => [wrapCode ? EditorView.lineWrapping : [], EditorView.darkTheme.of(isLightTheme === false)],
        [wrapCode, isLightTheme]
    )

    const blameDecorations = useMemo(() => (blameHunks ? [showGitBlameDecorations.of(blameHunks)] : []), [blameHunks])

    const preloadGoToDefinition = useExperimentalFeatures(features => features.preloadGoToDefinition ?? false)

    // Keep history and location in a ref so that we can use the latest value in
    // the onSelection callback without having to recreate it and having to
    // reconfigure the editor extensions
    const historyRef = useRef(history)
    historyRef.current = history
    const locationRef = useRef(location)
    locationRef.current = location

    const customHistoryAction = props.nav
    const onSelection = useCallback(
        (range: SelectedLineRange) => {
            const parameters = new URLSearchParams(locationRef.current.search)
            parameters.delete('popover')

            let query: string | undefined

            if (range?.line !== range?.endLine && range?.endLine) {
                query = toPositionOrRangeQueryParameter({
                    range: {
                        start: { line: range.line },
                        end: { line: range.endLine },
                    },
                })
            } else if (range?.line) {
                query = toPositionOrRangeQueryParameter({ position: { line: range.line } })
            }

            const newSearchParameters = addLineRangeQueryParameter(parameters, query)
            if (customHistoryAction) {
                customHistoryAction(
                    historyRef.current.createHref({
                        ...locationRef.current,
                        search: formatSearchParameters(newSearchParameters),
                    })
                )
            } else {
                updateBrowserHistoryIfChanged(historyRef.current, locationRef.current, newSearchParameters)
            }
        },
        [customHistoryAction]
    )

    const extensions = useMemo(
        () => [
            staticExtensions,
            selectableLineNumbers({
                onSelection,
                initialSelection: position.line !== undefined ? position : null,
                navigateToLineOnAnyClick: navigateToLineOnAnyClick ?? false,
            }),
            tokenKeyboardNavigation
                ? tokensAsLinks({
                      history,
                      blobInfo,
                      preloadGoToDefinition,
                  })
                : [],
            syntaxHighlight.of(blobInfo),
            pin.init(() => (hasPin ? position : null)),
            extensionsController !== null && !navigateToLineOnAnyClick
                ? sourcegraphExtensions({
                      blobInfo,
                      initialSelection: position,
                      extensionsController,
                      disableStatusBar,
                      disableDecorations,
                  })
                : [],
            blobPropsCompartment.of(blobProps),
            blameDecorationsCompartment.of(blameDecorations),
            settingsCompartment.of(settings),
            search({
                // useFileSearch is not a dependency because the search
                // extension manages its own state. This is just the initial
                // value
                overrideBrowserFindInPageShortcut: useFileSearch,
                onOverrideBrowserFindInPageToggle: setUseFileSearch,
            }),
        ],
        // A couple of values are not dependencies (blameDecorations, blobProps,
        // hasPin, position and settings) because those are updated in effects
        // further below. However they are still needed here because we need to
        // set initial values when we re-initialize the editor.
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [onSelection, blobInfo, extensionsController, disableStatusBar, disableDecorations]
    )

    const editorRef = useRef<EditorView>()
    const editor = useCodeMirror(container, blobInfo.content, extensions, {
        updateValueOnChange: false,
        updateOnExtensionChange: false,
    })
    editorRef.current = editor

    // Make gutters content visible for the screen readers
    useEffect(() => {
        if (editor) {
            editor.dom.querySelector('.cm-gutters')?.removeAttribute('aria-hidden')
        }
    }, [editor])

    // Reconfigure editor when blobInfo or core extensions changed
    useEffect(() => {
        if (editor) {
            // We use setState here instead of dispatching a transaction because
            // the new document has nothing to do with the previous one and so
            // any existing state should be discarded.
            editor.setState(
                EditorState.create({
                    doc: blobInfo.content,
                    extensions,
                })
            )
        }
        // editor is not provided because this should only be triggered after the
        // editor was created (i.e. not on first render)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [blobInfo, extensions])

    // Propagate props changes to extensions
    useEffect(() => {
        if (editor) {
            editor.dispatch({ effects: blobPropsCompartment.reconfigure(blobProps) })
        }
        // editor is not provided because this should only be triggered after the
        // editor was created (i.e. not on first render)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [blobProps])

    // Update blame information
    useEffect(() => {
        if (editor) {
            editor.dispatch({ effects: blameDecorationsCompartment.reconfigure(blameDecorations) })
        }
        // editor is not provided because this should only be triggered after the
        // editor was created (i.e. not on first render)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [blameDecorations])

    // Update settings
    useEffect(() => {
        if (editor) {
            editor.dispatch({ effects: settingsCompartment.reconfigure(settings) })
        }
        // editor is not provided because this should only be triggered after the
        // editor was created (i.e. not on first render)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [settings])

    // Update selected lines when URL changes
    useEffect(() => {
        if (editor) {
            selectLines(editor, position.line ? position : null)
        }
        // editor is not provided because this should only be triggered after the
        // editor was created (i.e. not on first render)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [position])

    // Update pinned hovercard range
    useEffect(() => {
        if (editor && (!hasPin || (position.line && isValidLineRange(position, editor.state.doc)))) {
            // Only update range if position is valid inside the document.
            updatePin(editor, hasPin ? position : null)
        }
        // editor is not provided because this should only be triggered after the
        // editor was created (i.e. not on first render)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [position, hasPin])

    const openSearch = useCallback(() => {
        if (editorRef.current) {
            openSearchPanel(editorRef.current)
        }
    }, [])

    return (
        <>
            <div
                ref={setContainer}
                aria-label={ariaLabel}
                role={role}
                data-testid={dataTestId}
                className={`${className} overflow-hidden test-editor`}
                data-editor="codemirror6"
            />
            {overrideBrowserSearchKeybinding && useFileSearch && (
                <Shortcut ordered={['f']} held={['Mod']} onMatch={openSearch} ignoreInput={true} />
            )}
        </>
    )
}

/**
 * Returns true when the URL indicates that the hovercard at the URL position
 * should be shown on load (the hovercard is "pinned").
 */
function urlIsPinned(search: string): boolean {
    return new URLSearchParams(search).get('popover') === 'pinned'
}

/**
 * Helper hook to prevent resetting the editor view if the blob contents hasn't
 * changed.
 */
function useDistinctBlob(blobInfo: BlobInfo): BlobInfo {
    const blobRef = useRef(blobInfo)
    return useMemo(() => {
        if (!isEqual(blobRef.current, blobInfo)) {
            blobRef.current = blobInfo
        }
        return blobRef.current
    }, [blobInfo])
}
