// client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
<svelte:options immutable />

<script lang="ts">
    import Icon from '$lib/Icon.svelte'
    import { featureFlag } from '$lib/featureflags'
    import { displayRepoName, getRepoMatchUrl, type RepositoryMatch } from '$lib/shared'
    import { mdiArchive, mdiLock, mdiSourceFork } from '@mdi/js'
    import CodeHostIcon from './CodeHostIcon.svelte'

    import SearchResult from './SearchResult.svelte'
    import { Badge } from '$lib/wildcard'
    import { getSearchResultsContext } from './searchResultsContext'
    import { limitDescription, getMetadata, buildSearchURLQueryForMeta, simplifyLineRange } from '$lib/search/results'
    import { highlightRanges } from '$lib/dom'

    export let result: RepositoryMatch

    const enableRepositoryMetadata = featureFlag('repository-metadata')
    const queryState = getSearchResultsContext().queryState

    $: repoAtRevisionURL = getRepoMatchUrl(result)
    $: metadata = $enableRepositoryMetadata ? getMetadata(result) : []
    $: description = limitDescription(result.description ?? '')
    $: repoName = displayRepoName(result.repository)

    $: repositoryMatches = result.repositoryMatches?.map(simplifyLineRange) ?? []
    $: if (repoName !== result.repository) {
        // We only display part of the repository name, therefore we have to
        // adjust the match ranges for highlighting
        const delta = result.repository.length - repoName.length
        repositoryMatches = repositoryMatches.map(([start, end]) => [start - delta, end - delta])
    }
    $: descriptionMatches = result.descriptionMatches?.map(simplifyLineRange) ?? []
</script>

<SearchResult>
    <CodeHostIcon slot="icon" repository={result.repository} />
    <div slot="title">
        <!-- #key is needed here to recreate the link because use:highlightRanges changes the DOM -->
        {#key repositoryMatches}
            <a href={repoAtRevisionURL} use:highlightRanges={{ ranges: repositoryMatches }}
                >{displayRepoName(result.repository)}</a
            >
        {/key}
        {#if result.fork}
            <span class="info">
                <Icon aria-label="Forked repository" svgPath={mdiSourceFork} inline />
                <small>Fork</small>
            </span>
        {/if}
        {#if result.archived}
            <span class="info">
                <Icon aria-label="Archived repository" svgPath={mdiArchive} inline />
                <small>Archive</small>
            </span>
        {/if}
        {#if result.private}
            <span class="info">
                <Icon aria-label="Private repository" svgPath={mdiLock} inline />
                <small>Private</small>
            </span>
        {/if}
    </div>
    {#if description}
        <!-- #key is needed here to recreate the paragraph because use:highlightRanges changes the DOM -->
        {#key description}
            <p class="p-2 m-0" use:highlightRanges={{ ranges: descriptionMatches }}>
                {limitDescription(description)}
            </p>
        {/key}
    {/if}
    {#if metadata.length > 0}
        <ul class="p-2">
            {#each metadata as meta}
                <li>
                    <Badge variant="outlineSecondary">
                        <a
                            slot="custom"
                            let:class={className}
                            class={className}
                            href="/search?{buildSearchURLQueryForMeta($queryState, meta)}"
                        >
                            <code
                                >{meta.key}{#if meta.value}:{meta.value}{/if}</code
                            >
                        </a>
                    </Badge>
                </li>
            {/each}
        </ul>
    {/if}
</SearchResult>

<style lang="scss">
    ul {
        margin: 0;
        list-style: none;
        display: flex;
        gap: 0.5rem;
        flex-wrap: wrap;

        code {
            color: var(--search-filter-keyword-color);
        }
    }

    .info {
        border-left: 1px solid var(--border-color);
        margin-left: 0.5rem;
        padding-left: 0.5rem;
    }
</style>

// client/branded/src/search-ui/components/RepoSearchResult.tsx
import React, { useEffect, useRef } from 'react'

import { mdiSourceFork, mdiArchive, mdiLock } from '@mdi/js'
import classNames from 'classnames'

import { highlightNode } from '@sourcegraph/common'
import { codeHostSubstrLength, displayRepoName } from '@sourcegraph/shared/src/components/RepoLink'
import { QueryState } from '@sourcegraph/shared/src/search'
import { getRepoMatchLabel, getRepoMatchUrl, RepositoryMatch } from '@sourcegraph/shared/src/search/stream'
import { Icon, Link } from '@sourcegraph/wildcard'

import { LastSyncedIcon } from './LastSyncedIcon'
import { RepoMetadata } from './RepoMetadata'
import { ResultContainer } from './ResultContainer'

import styles from './SearchResult.module.scss'

const REPO_DESCRIPTION_CHAR_LIMIT = 500

export interface RepoSearchResultProps {
    result: RepositoryMatch
    onSelect: () => void
    buildSearchURLQueryFromQueryState?: (queryParameters: BuildSearchQueryURLParameters) => string
    queryState?: QueryState
    containerClassName?: string
    as?: React.ElementType
    index: number
    enableRepositoryMetadata?: boolean
}

export const RepoSearchResult: React.FunctionComponent<RepoSearchResultProps> = ({
    result,
    onSelect,
    containerClassName,
    as,
    index,
    enableRepositoryMetadata,
    buildSearchURLQueryFromQueryState,
    queryState,
}) => {
    const repoDescriptionElement = useRef<HTMLDivElement>(null)
    const repoNameElement = useRef<HTMLAnchorElement>(null)

    const title = (
        <div className={styles.title}>
            <span className={classNames('test-search-result-label', styles.titleInner, styles.mutedRepoFileLink)}>
                <Link to={getRepoMatchUrl(result)} ref={repoNameElement} data-selectable-search-result="true">
                    {displayRepoName(getRepoMatchLabel(result))}
                </Link>
            </span>
        </div>
    )

    useEffect((): void => {
        if (repoNameElement.current && result.repository && result.repositoryMatches) {
            for (const range of result.repositoryMatches) {
                highlightNode(
                    repoNameElement.current as HTMLElement,
                    range.start.column - codeHostSubstrLength(result.repository),
                    range.end.column - range.start.column
                )
            }
        }

        if (repoDescriptionElement.current && result.descriptionMatches) {
            for (const range of result.descriptionMatches) {
                highlightNode(
                    repoDescriptionElement.current as HTMLElement,
                    range.start.column,
                    range.end.column - range.start.column
                )
            }
        }
    }, [
        result,
        result.repositoryMatches,
        repoNameElement,
        result.description,
        result.descriptionMatches,
        repoDescriptionElement,
    ])

    return (
        <ResultContainer
            index={index}
            title={title}
            resultType={result.type}
            onResultClicked={onSelect}
            repoName={result.repository}
            repoStars={result.repoStars}
            className={containerClassName}
            as={as}
        >
            <div data-testid="search-repo-result">
                <div className={classNames(styles.searchResultMatch, 'p-2 flex-column')}>
                    {result.repoLastFetched && <LastSyncedIcon lastSyncedTime={result.repoLastFetched} />}
                    <div className="d-flex align-items-center flex-row">
                        <div className={styles.matchType}>
                            <small>Repository match</small>
                        </div>
                        {result.fork && (
                            <>
                                <div className={styles.divider} />
                                <div>
                                    <Icon
                                        aria-label="Forked repository"
                                        className={classNames('flex-shrink-0 text-muted', styles.icon)}
                                        svgPath={mdiSourceFork}
                                    />
                                </div>
                                <div>
                                    <small>Fork</small>
                                </div>
                            </>
                        )}
                        {result.archived && (
                            <>
                                <div className={styles.divider} />
                                <div>
                                    <Icon
                                        aria-label="Archived repository"
                                        className={classNames('flex-shrink-0 text-muted', styles.icon)}
                                        svgPath={mdiArchive}
                                    />
                                </div>
                                <div>
                                    <small>Archived</small>
                                </div>
                            </>
                        )}
                        {result.private && (
                            <>
                                <div className={styles.divider} />
                                <div>
                                    <Icon
                                        aria-label="Private repository"
                                        className={classNames('flex-shrink-0 text-muted', styles.icon)}
                                        svgPath={mdiLock}
                                    />
                                </div>
                                <div>
                                    <small>Private</small>
                                </div>
                            </>
                        )}
                    </div>
                    {enableRepositoryMetadata && !!result.metadata && (
                        <RepoMetadata
                            small={true}
                            className="mt-1"
                            queryState={queryState}
                            buildSearchURLQueryFromQueryState={buildSearchURLQueryFromQueryState}
                            items={Object.entries(result.metadata).map(([key, value]) => ({ key, value }))}
                        />
                    )}
                    {result.description && (
                        <>
                            <div className={styles.dividerVertical} />
                            <div>
                                <small>
                                    <em ref={repoDescriptionElement}>
                                        {result.description.length > REPO_DESCRIPTION_CHAR_LIMIT
                                            ? result.description.slice(0, REPO_DESCRIPTION_CHAR_LIMIT) + ' ...'
                                            : result.description}
                                    </em>
                                </small>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </ResultContainer>
    )
}
