// client/shared/src/components/CodeExcerpt.tsx
import classNames from 'classnames'
import { range, isEqual } from 'lodash'
import AlertCircleIcon from 'mdi-react/AlertCircleIcon'
import React from 'react'
import VisibilitySensor from 'react-visibility-sensor'
import { of, combineLatest, Observable, Subject, Subscription } from 'rxjs'
import { catchError, filter, switchMap, map, distinctUntilChanged } from 'rxjs/operators'

import { asError, ErrorLike, highlightNode, isErrorLike } from '@sourcegraph/common'
import { Repo } from '@sourcegraph/shared/src/util/url'

import * as GQL from '../schema'

import styles from './CodeExcerpt.module.scss'

export interface FetchFileParameters {
    repoName: string
    commitID: string
    filePath: string
    disableTimeout?: boolean
    ranges: GQL.IHighlightLineRange[]
}

interface Props extends Repo {
    commitID: string
    filePath: string
    highlightRanges: HighlightRange[]
    /** The 0-based (inclusive) line number that this code excerpt starts at */
    startLine: number
    /** The 0-based (exclusive) line number that this code excerpt ends at */
    endLine: number
    /** Whether or not this is the first result being shown or not. */
    isFirst: boolean
    className?: string
    /** A function to fetch the range of lines this code excerpt will display. It will be provided
     * the same start and end lines properties that were provided as component props */
    fetchHighlightedFileRangeLines: (isFirst: boolean, startLine: number, endLine: number) => Observable<string[]>
    blobLines?: string[]
}

interface HighlightRange {
    /**
     * The 0-based line number that this highlight appears in
     */
    line: number
    /**
     * The 0-based character offset to start highlighting at
     */
    character: number
    /**
     * The number of characters to highlight
     */
    highlightLength: number
}

interface State {
    blobLinesOrError?: string[] | ErrorLike
}

/**
 * A code excerpt that displays syntax highlighting and match range highlighting.
 */
export class CodeExcerpt extends React.PureComponent<Props, State> {
    public state: State = {}
    private tableContainerElement: HTMLElement | null = null
    private propsChanges = new Subject<Props>()
    private visibilityChanges = new Subject<boolean>()
    private subscriptions = new Subscription()
    private visibilitySensorOffset = { bottom: -500 }

    constructor(props: Props) {
        super(props)
        this.subscriptions.add(
            combineLatest([this.propsChanges, this.visibilityChanges])
                .pipe(
                    filter(([, isVisible]) => isVisible),
                    map(([props]) => props),
                    distinctUntilChanged((a, b) => isEqual(a, b)),
                    switchMap(({ blobLines, isFirst, startLine, endLine }) =>
                        blobLines ? of(blobLines) : props.fetchHighlightedFileRangeLines(isFirst, startLine, endLine)
                    ),
                    catchError(error => [asError(error)])
                )
                .subscribe(blobLinesOrError => {
                    this.setState({ blobLinesOrError })
                })
        )
    }

    public componentDidMount(): void {
        this.propsChanges.next(this.props)
    }

    public componentDidUpdate(): void {
        this.propsChanges.next(this.props)

        if (this.tableContainerElement) {
            const visibleRows = this.tableContainerElement.querySelectorAll('table tr')
            for (const highlight of this.props.highlightRanges) {
                // Select the HTML row in the excerpt that corresponds to the line to be highlighted.
                // highlight.line is the 0-indexed line number in the code file, and this.props.startLine is the 0-indexed
                // line number of the first visible line in the excerpt. So, subtract this.props.startLine
                // from highlight.line to get the correct 0-based index in visibleRows that holds the HTML row.
                const tableRow = visibleRows[highlight.line - this.props.startLine]
                if (tableRow) {
                    // Take the lastChild of the row to select the code portion of the table row (each table row consists of the line number and code).
                    const code = tableRow.lastChild as HTMLTableDataCellElement
                    highlightNode(code, highlight.character, highlight.highlightLength)
                }
            }
        }
    }

    public componentWillUnmount(): void {
        this.subscriptions.unsubscribe()
    }

    private onChangeVisibility = (isVisible: boolean): void => {
        this.visibilityChanges.next(isVisible)
    }

    public render(): JSX.Element | null {
        return (
            <VisibilitySensor
                onChange={this.onChangeVisibility}
                partialVisibility={true}
                offset={this.visibilitySensorOffset}
            >
                <code
                    data-testid="code-excerpt"
                    className={classNames(
                        styles.codeExcerpt,
                        this.props.className,
                        isErrorLike(this.state.blobLinesOrError) && styles.codeExcerptError
                    )}
                >
                    {this.state.blobLinesOrError && !isErrorLike(this.state.blobLinesOrError) && (
                        <div
                            ref={this.setTableContainerElement}
                            dangerouslySetInnerHTML={{ __html: this.makeTableHTML(this.state.blobLinesOrError) }}
                        />
                    )}
                    {this.state.blobLinesOrError && isErrorLike(this.state.blobLinesOrError) && (
                        <div className={styles.codeExcerptAlert}>
                            <AlertCircleIcon className="icon-inline mr-2" />
                            {this.state.blobLinesOrError.message}
                        </div>
                    )}
                    {!this.state.blobLinesOrError && (
                        <table>
                            <tbody>
                                {range(this.props.startLine, this.props.endLine).map(index => (
                                    <tr key={index}>
                                        <td className="line">{index + 1}</td>
                                        {/* create empty space to fill viewport (as if the blob content were already fetched, otherwise we'll overfetch) */}
                                        <td className="code"> </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    )}
                </code>
            </VisibilitySensor>
        )
    }

    private setTableContainerElement = (reference: HTMLElement | null): void => {
        this.tableContainerElement = reference
    }

    private makeTableHTML(blobLines: string[]): string {
        return '<table>' + blobLines.join('') + '</table>'
    }
}

// client/web-sveltekit/src/routes/search/CodeExcerpt.svelte
<script lang="ts">
    import '@sourcegraph/wildcard/src/global-styles/highlight.scss'

    import range from 'lodash/range'
    import { of, type Observable } from 'rxjs'
    import { catchError } from 'rxjs/operators'

    import { asError, isErrorLike, highlightNodeMultiline } from '$lib/common'
    import type { MatchGroupMatch } from '$lib/shared'
    import { observeIntersection } from '$lib/intersection-observer'

    export let startLine: number
    export let endLine: number
    export let fetchHighlightedFileRangeLines: (startLine: number, endLine: number) => Observable<string[]>
    export let blobLines: string[] | undefined = undefined
    export let matches: MatchGroupMatch[] = []

    let blobLinesOrError: string[] | Error | undefined = undefined

    function highlightRanges(node: HTMLElement, matches: MatchGroupMatch[]) {
        const visibleRows = node.querySelectorAll<HTMLTableRowElement>('tr')
        for (const highlight of matches) {
            // Select the HTML rows in the excerpt that correspond to the first and last line to be highlighted.
            // highlight.startLine is the 0-indexed line number in the code file, and startLine is the 0-indexed
            // line number of the first visible line in the excerpt. So, subtract startLine
            // from highlight.startLine to get the correct 0-based index in visibleRows that holds the HTML row
            // where highlighting should begin. Subtract startLine from highlight.endLine to get the correct 0-based
            // index in visibleRows that holds the HTML row where highlighting should end.
            const startRowIndex = highlight.startLine - startLine
            const endRowIndex = highlight.endLine - startLine
            const startRow = visibleRows[startRowIndex]
            const endRow = visibleRows[endRowIndex]
            if (startRow && endRow) {
                highlightNodeMultiline(
                    visibleRows,
                    startRow,
                    endRow,
                    startRowIndex,
                    endRowIndex,
                    highlight.startCharacter,
                    highlight.endCharacter
                )
            }
        }
    }

    let isVisible = false

    function onIntersection(event: { detail: boolean }) {
        isVisible = event.detail
    }

    $: if (isVisible) {
        const observable = blobLines ? of(blobLines) : fetchHighlightedFileRangeLines(startLine, endLine)
        observable.pipe(catchError(error => [asError(error)])).subscribe(_blobLinesOrError => {
            blobLinesOrError = _blobLinesOrError
        })
    }
</script>

<code use:observeIntersection on:intersecting={onIntersection}>
    {#if blobLinesOrError && !isErrorLike(blobLinesOrError)}
        {#key blobLinesOrError}
            <table use:highlightRanges={matches}>
                {@html blobLinesOrError.join('')}
            </table>
        {/key}
    {:else if !blobLinesOrError}
        <table>
            <tbody>
                {#each range(startLine, endLine) as index}
                    <tr>
                        <td class="line" data-line={index + 1} />
                        <!--create empty space to fill viewport (as if the blob content were already fetched, otherwise we'll overfetch) -->
                        <td class="code" />
                    </tr>
                {/each}
            </tbody>
        </table>
    {/if}
</code>

<style lang="scss">
    code {
        display: flex;
        align-items: center;
        padding: 0.125rem 0.375rem;
        background-color: var(--background-color, --code-bg);
        overflow-x: auto;

        font-family: var(--code-font-family);
        font-size: var(--code-font-size);
        line-height: 1rem;
        white-space: pre;

        :global(td.line::before) {
            content: attr(data-line);
            color: var(--text-muted);
        }

        :global(td.code) {
            white-space: pre;
            padding-left: 1rem;
        }
    }
</style>
