// client/wildcard/src/components/Badge/Badge.tsx
import classNames from 'classnames'
import React from 'react'

import styles from './Badge.module.scss'
import { BADGE_VARIANTS } from './constants'

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
    /**
     * The variant style of the badge.
     */
    variant?: typeof BADGE_VARIANTS[number]
    /**
     * Allows modifying the size of the badge. Supports a smaller variant.
     */
    small?: boolean
    /**
     * Render the badge as a rounded pill
     */
    pill?: boolean
    /**
     * Additional text to display on hover
     */
    tooltip?: string
    /**
     * Used to render the badge as a link to a specific URL
     */
    href?: string
    /**
     * If the Badge should not use any branded styles
     */
    unstyled?: boolean
    /**
     * Used to change the element that is rendered.
     */
    as?: React.ElementType
    className?: string
}

/**
 * An abstract UI component which renders a small "badge" with specific styles to help annotate content.
 */
export const Badge: React.FunctionComponent<BadgeProps> = ({
    children,
    variant,
    small,
    pill,
    tooltip,
    className,
    unstyled,
    href,
    as: Component = 'span',
    ...otherProps
}) => {
    const brandedClassName =
        !unstyled && classNames(styles.badge, variant && styles[variant], small && styles.sm, pill && styles.pill)

    const commonProps = {
        'data-tooltip': tooltip,
        className: classNames(brandedClassName, className),
        ...otherProps,
    }

    if (href) {
        return (
            <a href={href} rel="noopener" target="_blank" {...commonProps}>
                {children}
            </a>
        )
    }

    return <Component {...commonProps}>{children}</Component>
}

// client/web-sveltekit/src/lib/wildcard/Badge.svelte
<script lang="ts" context="module">
    import classNames from 'classnames'
    import styles from './Badge.module.scss'

    export const BADGE_VARIANTS = [
        'primary',
        'secondary',
        'success',
        'danger',
        'warning',
        'info',
        'merged',
        'outlineSecondary',
        'link',
    ] as const

    export type BadgeVariantType = typeof BADGE_VARIANTS[number]

    export function badgeClassName(variant: BadgeVariantType, small?: boolean, pill?: boolean): string {
        return classNames(styles.badge, styles[variant], { [styles.small]: small, [styles.pill]: pill })
    }
</script>

<script lang="ts">
    /**
     * The variant style of the badge.
     */
    export let variant: BadgeVariantType
    /**
     * Allows modifying the size of the badge. Supports a smaller variant.
     */
    export let small: boolean | undefined = undefined
    /**
     * Render the badge as a rounded pill
     */
    export let pill: boolean | undefined = undefined

    $: cls = badgeClassName(variant, small, pill)
</script>

<!--TODO: support non-branded badges -->
<slot name="custom" class={cls}>
    <span class={cls} data-badge>
        <slot />
    </span>
</slot>
