// client/web/src/components/DismissibleAlert/DismissibleAlert.tsx
import * as React from 'react'

import { mdiClose } from '@mdi/js'
import classNames from 'classnames'

import { Button, Alert, AlertProps, Icon } from '@sourcegraph/wildcard'

import styles from './DismissibleAlert.module.scss'

export interface DismissibleAlertProps extends AlertProps {
    /**
     * If provided, used to build the key that represents the alert in local storage. An
     * alert with a storage key will be permanently dismissed once the user dismisses it.
     */
    partialStorageKey?: string

    testId?: string
}

/**
 * A global site alert that can be dismissed. If a `partialStorageKey` is provided, the
 * alert will never be shown again after it is dismissed. Otherwise, it will be shown
 * whenever unmounted and remounted.
 */
export const DismissibleAlert: React.FunctionComponent<React.PropsWithChildren<DismissibleAlertProps>> = ({
    partialStorageKey,
    className,
    testId,
    children,
    variant,
}) => {
    const [dismissed, setDismissed] = React.useState<boolean>(
        partialStorageKey ? isAlertDismissed(partialStorageKey) : false
    )

    const onDismiss = React.useCallback(() => {
        if (partialStorageKey) {
            dismissAlert(partialStorageKey)
        }
        setDismissed(true)
    }, [partialStorageKey])

    if (dismissed) {
        return null
    }

    return (
        <Alert data-testid={testId} className={classNames(styles.container, className)} variant={variant}>
            <div className={styles.content}>{children}</div>
            <Button aria-label="Close alert" variant="icon" className={styles.closeButton} onClick={onDismiss}>
                <Icon aria-hidden={true} svgPath={mdiClose} />
            </Button>
        </Alert>
    )
}

export function dismissAlert(key: string): void {
    localStorage.setItem(storageKeyForPartial(key), 'true')
}

export function isAlertDismissed(key: string): boolean {
    return localStorage.getItem(storageKeyForPartial(key)) === 'true'
}

function storageKeyForPartial(partialStorageKey: string): string {
    return `DismissibleAlert/${partialStorageKey}/dismissed`
}

// client/web-sveltekit/src/lib/global-notifications/DismissibleAlert.svelte
<script lang="ts" context="module">
    import classNames from 'classnames'

    function dismissAlert(key: string): void {
        localStorage.setItem(storageKeyForPartial(key), 'true')
    }

    function isAlertDismissed(key: string): boolean {
        return localStorage.getItem(storageKeyForPartial(key)) === 'true'
    }

    function storageKeyForPartial(partialStorageKey: string): string {
        return `DismissibleAlert/${partialStorageKey}/dismissed`
    }
</script>

<script lang="ts">
    import {mdiClose} from '@mdi/js'
    import Icon from '$lib/Icon.svelte'
    import {Alert, Button} from '$lib/wildcard'

    export let variant: 'info' | 'danger'
    export let partialStorageKey: string

    let className = '';
    export {className as class};

    // Local state
    let dismissed = partialStorageKey ? isAlertDismissed(partialStorageKey) : false;

    // Callback handlers
    function handleDismissClick() {
        if (partialStorageKey) {
            dismissAlert(partialStorageKey)
        }

        dismissed = true
    }
</script>

{#if !dismissed}
    <Alert class={classNames('root', className)} variant={variant}>

        <div class='content'>
            <slot/>
        </div>

        <Button
                variant="icon"
                aria-label="Dismiss alert"
                on:click={handleDismissClick}
        >
            <Icon aria-hidden={true} svgPath={mdiClose}/>
        </Button>
    </Alert>
{/if}

<style lang="scss">
  .root {
    display: flex;
    align-items: flex-start;
    padding-right: 0.5rem;
  }

  .content {
    display: flex;
    flex: 1 1 auto;
    line-height: (20/14);
  }

  .root > :global(.close-button) {
    height: 1.25rem;
    color: var(--icon-color);
  }
</style>
