// client/web-sveltekit/src/lib/Timestamp.svelte
<script lang="ts" context="module">
    function formatDate(date: Date, options: { utc?: boolean }): string {
        if (options.utc) {
            date = addMinutes(date, date.getTimezoneOffset())
        }
        const dateHasTime = date.toString().includes('T')
        const defaultFormat = dateHasTime ? TimestampFormat.FULL_DATE_TIME : TimestampFormat.FULL_DATE
        return format(date, defaultFormat) + (options.utc ? ' UTC' : '')
    }

    enum TimestampFormat {
        FULL_TIME = 'HH:mm:ss',
        FULL_DATE = 'yyyy-MM-dd',
        FULL_DATE_TIME = 'yyyy-MM-dd pp',
    }
</script>

<script lang="ts">
    import { addMinutes, format, formatDistance, formatDistanceStrict } from 'date-fns'
    import { currentDate } from './stores'
    import Tooltip from './Tooltip.svelte'

    /** The date (if string, in ISO 8601 format). */
    export let date: Date | string

    /** Use exact timestamps (i.e. omit "less than", "about", etc.) */
    export let strict: boolean = false

    /** Show absolute timestamp and show relative timestamp in label*/
    export let showAbsolute: boolean = false

    /** Hide suffix (e.g. ago) */
    export let hideSuffix: boolean = false

    /** Show time in UTC */
    export let utc: boolean | undefined = undefined

    $: dateObj = typeof date === 'string' ? new Date(date) : date
    $: formattedDate = formatDate(dateObj, { utc })
    $: relativeDate = (strict ? formatDistanceStrict : formatDistance)(dateObj, $currentDate, {
        addSuffix: !hideSuffix,
    })
</script>

<Tooltip tooltip={showAbsolute ? relativeDate : formattedDate}>
    <span class="timestamp" data-testid="timestamp">{showAbsolute ? formattedDate : relativeDate} </span></Tooltip
>

// client/web/src/components/time/Timestamp.tsx
import React, { useEffect, useMemo, useState } from 'react'

import { format, addMinutes, parseISO } from 'date-fns'
import formatDistance from 'date-fns/formatDistance'
import formatDistanceStrict from 'date-fns/formatDistanceStrict'

import { Tooltip } from '@sourcegraph/wildcard'

interface Props {
    /** The date (if string, in ISO 8601 format). */
    date: string | Date | number

    /** Omit the "about". */
    noAbout?: boolean

    /** Function that returns the current time (for stability in visual tests). */
    now?: () => Date

    /** Whether to use exact timestamps (i.e. omit "less than", "about", etc.) */
    strict?: boolean

    /** Whether to show absolute timestamp and show relative one in tooltip */
    preferAbsolute?: boolean

    /** Optional semantic timestamp format */
    timestampFormat?: TimestampFormat

    utc?: boolean
}

export enum TimestampFormat {
    FULL_TIME = 'HH:mm:ss',
    FULL_DATE = 'yyyy-MM-dd',
    FULL_DATE_TIME = 'yyyy-MM-dd pp',
}

const RERENDER_INTERVAL_MSEC = 7000

/**
 * Displays a date's relative time ("... ago") and shows the full date on hover. Re-renders
 * periodically to ensure the relative time string is up-to-date.
 */
export const Timestamp: React.FunctionComponent<React.PropsWithChildren<Props>> = ({
    date,
    noAbout = false,
    strict = false,
    now = Date.now,
    preferAbsolute = false,
    timestampFormat,
    utc = false,
}) => {
    const [label, setLabel] = useState<string>(calculateLabel(date, now, strict, noAbout))
    useEffect(() => {
        const intervalHandle = window.setInterval(
            () => setLabel(calculateLabel(date, now, strict, noAbout)),
            RERENDER_INTERVAL_MSEC
        )
        return () => {
            window.clearInterval(intervalHandle)
        }
    }, [date, noAbout, now, strict])


    const tooltip = useMemo(() => {
        let parsedDate = typeof date === 'string' ? parseISO(date) : new Date(date)
        if (utc) {
            parsedDate = addMinutes(parsedDate, parsedDate.getTimezoneOffset())
        }
        const dateHasTime = date.toString().includes('T')
        const defaultFormat = dateHasTime ? TimestampFormat.FULL_DATE_TIME : TimestampFormat.FULL_DATE
        return format(parsedDate, timestampFormat ?? defaultFormat) + (utc ? " UTC" : "")
    }, [date, timestampFormat, utc])

    return (
        <Tooltip content={preferAbsolute ? label : tooltip}>
            <span className="timestamp">{preferAbsolute ? tooltip : label}</span>
        </Tooltip>
    )
}

function calculateLabel(
    date: string | Date | number,
    now: () => Date | number,
    strict: boolean,
    noAbout: boolean
): string {
    let label: string
    if (strict) {
        label = formatDistanceStrict(typeof date === 'string' ? parseISO(date) : date, now(), {
            addSuffix: true,
        })
    } else {
        label = formatDistance(typeof date === 'string' ? parseISO(date) : date, now(), {
            addSuffix: true,
            includeSeconds: true,
        })
    }
    if (noAbout) {
        label = label.replace('about ', '')
    }
    return label
}
