// client/web/src/enterprise/catalog/pages/component/code/LastCommit.tsx
import classNames from 'classnames'
import React from 'react'
import { Link } from 'react-router-dom'

import { Timestamp } from '../../../../../components/time/Timestamp'
import { ComponentDetailFields } from '../../../../../graphql-operations'
import { PersonLink } from '../../../../../person/PersonLink'
import { UserAvatar } from '../../../../../user/UserAvatar'

export const LastCommit: React.FunctionComponent<{
    commit: NonNullable<ComponentDetailFields['commits']>['nodes'][0]
    after?: React.ReactFragment
    className?: string
}> = ({ commit, after, className }) => (
    <div className={classNames('d-flex align-items-center', className)}>
        <UserAvatar className="icon-inline mr-2 flex-shrink-0" user={commit.author.person} size={18} />
        <PersonLink person={commit.author.person} className="font-weight-bold mr-2 flex-shrink-0" />
        <Link to={commit.url} className="text-truncate flex-grow-1 text-body mr-2" title={commit.message}>
            {commit.subject}
        </Link>
        <small className="text-nowrap text-muted">
            <Link to={commit.url} className="text-monospace text-muted mr-2 d-none d-md-inline">
                {commit.abbreviatedOID}
            </Link>
            <Timestamp date={commit.author.date} noAbout={true} />
        </small>
        {after}
    </div>
)

// client/web-sveltekit/src/lib/repo/LastCommit.svelte
<script lang="ts">
    import Avatar from '$lib/Avatar.svelte'
    import Timestamp from '$lib/Timestamp.svelte'

    import type { LastCommitFragment } from './LastCommit.gql'

    export let lastCommit: LastCommitFragment

    $: user = lastCommit.author.person
    $: canonicalURL = lastCommit.canonicalURL
    $: commitMessage = lastCommit.subject
</script>

<div class="last-commit">
    <Avatar avatar={user} --avatar-size="1.5rem" />
    <span>{user.displayName || user.name}</span>
    <a href={canonicalURL}>
        {commitMessage}
    </a>
    <span class="timestamp"><Timestamp date={lastCommit.author.date} /></span>
</div>

<style lang="scss">
    .last-commit {
        display: flex;
        align-items: center;
        gap: 0.75rem;
        white-space: nowrap;
        font-size: var(--font-size-small);
    }

    a {
        color: var(--text-muted);
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .timestamp {
        color: var(--text-muted);
    }
</style>
