// client/search-ui/src/input/codemirror/Suggestions.svelte
<svelte:options immutable />

<script lang="ts">
    import { Group, Option } from './suggestions'
    import Icon from './Icon.svelte'
    import { createEventDispatcher } from 'svelte'

    export let id: string
    export let results: Group[]
    export let activeRowIndex = -1
    export let open = false

    let dispatch = createEventDispatcher<{ select: Option }>()
    let container: HTMLElement
    let windowHeight: number

    $: maxHeight = container ? windowHeight - container.getBoundingClientRect().top - 20 : 'auto'
    $: flattenedRows = results.flatMap(group => group.entries)
    $: focusedItem = flattenedRows[activeRowIndex]
    $: show = open && results.length > 0

    function handleSelection(event: MouseEvent) {
        const match = (event.target as HTMLElement).closest('li[role="row"]')?.id.match(/\d+x\d+/)
        if (match) {
            const [group, option] = match[0].split('x')
            dispatch('select', results[+group].entries[+option])
        }
    }

    function getNote(option: Option): string {
        switch (option.type) {
            case 'completion':
                return 'Add'
            case 'target':
                return 'Jump to'
            case 'command':
                return option.note ?? ''
        }
    }
</script>

<svelte:window bind:innerHeight={windowHeight} />
{#if show}
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <div {id} role="grid" style="max-height: {maxHeight}px" on:mousedown={handleSelection} bind:this={container}>
        {#each results as group, groupIndex (group.title)}
            <ul role="rowgroup" aria-labelledby="{id}-{groupIndex}-label">
                <li id="{id}-{groupIndex}-label" role="presentation">{group.title}</li>
                {#each group.entries as option, rowIndex (option)}
                    <li role="row" id="{id}-{groupIndex}x{rowIndex}" aria-selected={focusedItem === option}>
                        {#if option.icon}
                            <div class="pr-1">
                                <Icon path={option.icon} />
                            </div>
                        {/if}
                        <div role="gridcell" class="content">
                            {#if option.render}
                                <svelte:component this={option.render} {option} />
                            {:else if option.matches}
                                {#each option.value as char, index}
                                    {#if option.matches.has(index)}
                                        <span class="match">{char}</span>
                                    {:else}
                                        {char}
                                    {/if}
                                {/each}
                            {:else}
                                {option.value}
                            {/if}
                        </div>
                        {#if option.description}
                            <div role="gridcell" class="description">
                                {option.description}
                            </div>
                        {/if}
                        <div role="gridcell" class="note">
                            {getNote(option)}
                        </div>
                    </li>
                {/each}
            </ul>
        {/each}
    </div>
{/if}

<style lang="scss">
    [role='grid'] {
        overflow-y: auto;
    }

    ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }

    [role='rowgroup'] {
        border-bottom: 1px solid var(--border-color);
        padding: 12px;

        &:first-of-type {
            padding-top: 0;
        }

        &:last-of-type {
            border: none;
        }

        &:last-of-type {
            border: none;
        }

        // group header
        [role='presentation'] {
            color: var(--text-muted);
            font-size: 12px;
            font-weight: 500;
            margin-bottom: 0.25rem;
            padding: 0 8px;
        }

        [role='row'] {
            display: flex;
            align-items: center;
            padding: 4px 8px;
            border-radius: var(--border-radius);
            font-family: var(--code-font-family);
            font-size: 12px;
            min-height: 24px;

            &[aria-selected='true'] {
                background-color: var(--subtle-bg);
                border-radius: 4px;
            }

            &:hover {
                background-color: var(--color-bg-2);
                cursor: pointer;
            }

            .match {
                font-weight: bold;
            }

            .description {
                margin-left: 8px;
                color: var(--input-placeholder-color);
            }

            .note {
                font-size: 12px;
                margin-left: auto;
                color: var(--text-muted);
                font-family: var(--font-family-base);
            }
        }
    }
</style>

// client/search-ui/src/input/experimental/Suggestions.tsx
import React, { MouseEvent, useMemo, useState, useCallback, useEffect } from 'react'

import { Icon } from '@sourcegraph/wildcard'

import { SyntaxHighlightedSearchQuery } from '../../components'

import { Group, Option } from './suggestions'

import styles from './Suggestions.module.scss'

function getNote(option: Option): string {
    switch (option.type) {
        case 'completion':
            return 'Add'
        case 'target':
            return 'Jump to'
        case 'command':
            return option.note ?? ''
    }
}

function useWindowHeight(): number {
    const [height, setHeight] = useState(window.innerHeight)

    useEffect(() => {
        const handler = (): void => setHeight(window.innerHeight)
        window.addEventListener('resize', handler)

        return () => window.removeEventListener('resize', handler)
    }, [])

    return height
}

interface SuggesionsProps {
    id: string
    results: Group[]
    activeRowIndex: number
    open?: boolean
    onSelect(option: Option): void
}

export const Suggestions: React.FunctionComponent<SuggesionsProps> = ({
    id,
    results,
    activeRowIndex,
    onSelect,
    open = false,
}) => {
    const [container, setContainer] = useState<HTMLDivElement | null>(null)

    const handleSelection = useCallback(
        (event: MouseEvent) => {
            const match = (event.target as HTMLElement).closest('li[role="row"]')?.id.match(/\d+x\d+/)
            if (match) {
                const [group, option] = match[0].split('x')
                onSelect(results[+group].options[+option])
            }
        },
        [onSelect, results]
    )

    const windowHeight = useWindowHeight()
    const maxHeight = useMemo(
        () => (container ? `${windowHeight - container.getBoundingClientRect().top - 20}px` : 'auto'),
        [container, windowHeight]
    )
    const flattenedRows = useMemo(() => results.flatMap(group => group.options), [results])
    const focusedItem = flattenedRows[activeRowIndex]
    const show = open && results.length > 0

    if (!show) {
        return null
    }

    return (
        <div
            ref={setContainer}
            id={id}
            className={styles.suggestions}
            role="grid"
            // eslint-disable-next-line react/forbid-dom-props
            style={{ maxHeight }}
            onMouseDown={handleSelection}
            tabIndex={-1}
        >
            {results.map((group, groupIndex) => (
                <ul role="rowgroup" key={group.title} keyaria-labelledby={`${id}-${groupIndex}-label`}>
                    <li id={`${id}-${groupIndex}-label`} role="presentation">
                        {group.title}
                    </li>
                    {group.options.map((option, rowIndex) => (
                        <li
                            role="row"
                            key={rowIndex}
                            id={`${id}-${groupIndex}x${rowIndex}`}
                            aria-selected={focusedItem === option}
                        >
                            {option.icon && (
                                <div className="pr-1">
                                    <Icon className={styles.icon} svgPath={option.icon} aria-hidden="true" />
                                </div>
                            )}
                            <div role="gridcell">
                                {option.render
                                    ? option.render(option)
                                    : option.matches
                                    ? [...option.value].map((char, index) =>
                                          option.matches!.has(index) ? (
                                              <span className={styles.match}>{char}</span>
                                          ) : (
                                              char
                                          )
                                      )
                                    : option.value}
                            </div>
                            {option.description && (
                                <div role="gridcell" className={styles.description}>
                                    {option.description}
                                </div>
                            )}
                            <div role="gridcell" className={styles.note}>
                                {getNote(option)}
                            </div>
                        </li>
                    ))}
                </ul>
            ))}
        </div>
    )
}

export const FilterOption: React.FunctionComponent<{ option: Option }> = ({ option }) => (
    <span className={styles.filterOption}>
        {option.matches
            ? [...option.value].map((char, index) =>
                  option.matches!.has(index) ? <span className={styles.match}>{char}</span> : char
              )
            : option.value}
        <span className={styles.separator}>:</span>
    </span>
)

export const QueryOption: React.FunctionComponent<{ option: Option }> = ({ option }) => (
    <SyntaxHighlightedSearchQuery query={option.value} />
)
